fos_rest:
  param_fetcher_listener: true

  body_listener:
    decoders:
      json: fos_rest.decoder.json

  format_listener:
    enabled: true
    rules:
      - { path: '^/', priorities: ['json', 'xml'], fallback_format: 'json' }

  versioning: true
  view:
    view_response_listener: 'force'
    formats:
      json: true

