parameters:
    jms_serializer.camel_case_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy

jms_serializer:
    visitors:
        xml:
            format_output: '%kernel.debug%'
    metadata:
        auto_detection: false
        directories:
            app:
                namespace_prefix: "App"
                path: "%kernel.root_dir%/Resources/config/serializer"
    handlers:
        datetime:
            default_format: "Y-m-d H:i:s"
#            another-name:
#                namespace_prefix: "My\\BarBundle"
#                path: "@MyBarBundle/Resources/config/serializer"
